### ISSUE TITLE
Upgrade lodash?

### ISSUE THREAD

**Issue by anselmbradford** [hiddentao/fast-levenshtein#10]
I got this warning elsewhere `npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0`. Sounds like this [package](https://github.com/hiddentao/fast-levenshtein/blob/master/package.json#L14) is outdated.

**Comment by hiddentao** [comment]
Thanks, fixed in latest release.
