### ISSUE TITLE
Async version is not async

### ISSUE THREAD

**Issue by addaleax** [hiddentao/fast-levenshtein#11]
[This](https://github.com/hiddentao/fast-levenshtein/blob/master/levenshtein.js#L171) is **not** an asynchronous call (and does throw an exception in the current node.js master):
```js
setTimeout(__calculate(), 0);
```

You could use `setTimeout(__calculate, 0);`, but recursive `setTimeout` calls are slowed down (to avoid tasks hogging the CPU, I assume), which leads to timeouts in the test cases. Maybe just go for `setImmediate` or similar here?

**Comment by addaleax** [comment]
(The exception in node.js is due to nodejs/node#4362, with the very purpose of catching bugs like this)

**Comment by hiddentao** [comment]
Thanks, I'm surprised I didn't notice that before - that was totally wrong. That's now fixed. I've also set it so that it will use `process.nextTick()` instead if available.
