### ISSUE TITLE
Chinese bad recognition

### ISSUE THREAD

**Issue by Adavo** [hiddentao/fast-levenshtein#14]
console.log(window.Levenshtein.get('你好世界', '你好'));   
=> get 6, but is no what I am supposed to get, isn't it ? Or if yes then I don't understand how is calculated for simplified chinese character.

**Comment by hiddentao** [comment]
I just ran this locally and got 2.

**Comment by Adavo** [comment]
Found it why: if the file is encoded UTF8  (without BOM) then is 6, with is 2. Didn't pay attention to that.

**Comment by hiddentao** [comment]
Thanks. Pushed v2 with a slight performance update.
