### ISSUE TITLE
Lack of Intl support on Safari throws ReferenceError

### ISSUE THREAD

**Issue by vietqhoang** [hiddentao/fast-levenshtein#16]
Safari does not have [Intl support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_compatibility).

With the new `collator` addition the js throws the following error, `ReferenceError: Can't find variable: Intl`.

**Comment by hiddentao** [comment]
Fixed in 2.0.5
